apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-deployment
  labels:
    app: jenkins
spec:
  template:
    metadata:
      name: jenkins-dep
      labels:
        app: jenkins
    spec:
      containers:
        - name: jenkins
          image: jenkins/jenkins
  replicas: 2
  selector:
    matchLabels:
      app: jenkins
